### ISSUE TITLE
Add a basic map

### ISSUE THREAD

**Issue by sadmansk** [hinataiswaifu/live#1]
The map needs to be tile based:
* Each tile has certain properties, such as interactivity, collision properties, treadability (water, forest regions, flat grass)
* Basic map should just be 64x64 tiles, 16x16 pixels each.
* Camera should be centered, so map moves with the player.

**Comment by shanpls** [comment]
- Map files will include a layer indicating obstacle tiles

**Comment by sadmansk** [comment]
Closed by #17.
