### ISSUE TITLE
Add inventory system

### ISSUE THREAD

**Issue by sadmansk** [hinataiswaifu/live#2]
This task has two parts:
* The player object has support for the inventory system
* There are objects on the map that can be picked up by the player

These objects will have their own base type, initialized in some way to be different. The inventory itself will be a container for these objects.

**Comment by Jacqueuela** [comment]
Each inventory item have the following properties:
  - weight
  - image
Inventory items may have the following actions:
  - pickup
  - drop
  - use
  - consume (use with destruction)
MVP will include 2 types of items - food and water.
  - Both have the property of being consumable to sustain the player's hunger / thirst

The inventory system will be a tiling inventory system limited by weight.
