### ISSUE TITLE
Game HUD

### ISSUE THREAD

**Issue by Jacqueuela** [hinataiswaifu/live#6]
Implement a simple HUD for the game displaying:
- [x] Health and stamina bars for a given player
    - [x] Fixed at top of screen
    - [x] Above the character
- [x] Inventory Menu - w/ Jack
    - [x] Fixed size
    - [x] ~~Expandable - Scrollable (?)~~
- [x] Some sort of timer indicating date time OR how long the player has survived.
- [x] ~~Mini-map - Stretch Goal~~

**Comment by sadmansk** [comment]
*Updated with timer info*

**Comment by Jacqueuela** [comment]
Good Work Guys!

**Comment by sadmansk** [comment]
Closed by #18
